-- 코드를 입력하세요
SELECT USED_GOODS_BOARD.TITLE,USED_GOODS_BOARD.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, 
USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE  USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
        AND DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, "%Y-%m") = "2022-10"
ORDER BY USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE
# DATE_FORMAT 도 이제 쓰다보니 익숙해진다. 이문제도 그리고 이너조인 써도 될듯 싶다.
