-- 코드를 작성해주세요
SELECT COUNT(FISH_NAME_INFO.FISH_TYPE) AS FISH_COUNT,  FISH_NAME_INFO.FISH_NAME
FROM FISH_INFO, FISH_NAME_INFO
WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY FISH_COUNT DESC;

-- 어설프게 조인 쓰려다가 계속 틀림 
-- 일단은 기본기부터 다시 합시다.