-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER = "W" AND DATE_FORMAT(DATE_OF_BIRTH, "%m") = "03" AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC

-- DATE_FORMAT 은 알았다고 생각했는데 그냥 FORMAT으로 생각해서 계혹 틀리네