-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",USED_GOODS_FILE.BOARD_ID,"/",USED_GOODS_FILE.FILE_ID,USED_GOODS_FILE.FILE_NAME,USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD, USED_GOODS_FILE
WHERE USED_GOODS_BOARD.VIEWS = (SELECT MAX(USED_GOODS_BOARD.VIEWS) FROM USED_GOODS_BOARD) AND USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID
ORDER BY USED_GOODS_FILE.FILE_ID DESC;

-- Concat 처음써본듯, 다만 이것도 join이 더 깔끔하려나