SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN,'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도%"
ORDER BY WAREHOUSE_ID;

-- IFNULL, IS NULL, IS NOT NULL 헷갈리네, 심지어 NULL 엔 등호 연산 못쓰는 줄 이제 알았다.

-- 추가 풀이
-- SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
-- FROM FOOD_WAREHOUSE
-- WHERE ADDRESS LIKE "경기도%"
-- ORDER BY WAREHOUSE_ID;